/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as customRouterSol from "./CustomRouter.sol";
export type { customRouterSol };
export type { TestUSDC } from "./TestUSDC";
export type { WETH9 } from "./WETH9";
